### PR TITLE
XML -> Properties && Solved Issue #30

### PR DESCRIPTION
**Pull request by st3no**
- Replaced the configuration file from XML to Properties (less code and faster)
- Added variable to save 'last folder searched' [#30]

### CODE REVIEW

**Comment by mayuso** [comment]
This looks good, I specially like the idea of the new `.properties` format, thanks for solving #30 too. It compiles and looks good overall except for a couple things:

* If the executable doesn't find the `.properties` it throws the following exception, but does not create it or open the UI:

    java.io.FileNotFoundException: jmarkpad.properties
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at ui.UI.loadConfig(UI.java:101)
        at ui.UI.start(UI.java:70)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)

* The `.gitnigore` file should now contain `*.properties` instead of `*.xml`.

I'll test a bit more but everything else looks good. 

I will merge as soon as everything is fixed and tested.

Thank you.

**Comment by st3no** [comment]
Great!!, I will fix these bugs ^^, also I think it is better to ignore only 'jmarkpad.propertis' in place of any file with extension .properties, maybe they will serve in the future.

**Comment by mayuso** [comment]
I agree. Ignoring individual files might be our best option right now. We can manage it easily and adding new files in the future won't be a headache.

**Comment by st3no** [comment]
Properties file stuff fixed, changed the appearance of About.

**Comment by st3no** [comment]
I wronged the button, I did not want to close XD

**Comment by mayuso** [comment]
The missing file problem still exists:

    java.nio.file.NoSuchFileException: properties\default.properties

It is supposed to create `jmarkpad.properties` if it doesn't exist, as it did with the XML file. Also, why do you reference two diferent files? (Sometimes `jmarkpad.properties` and sometimes `properties\default.properties`)

Just create `jmarkpad.properties` if it doesn't exist with the default values, that way you avoid having 2 diferent files.

I'll review all the changes individually when I have some time to invest into it (Reviewing diferent changes inside a single commit is hard and slow).

Thank you for all the contributions, I am sorry that it might take me some time to go through all of these, I have other priorities (work for the most part) right now, but I promise I will take the time to do this ASAP.

**Comment by mayuso** [comment]
I forgot to mention:

These are significant changes, feel free to add your name to the Authors section in the README if you are interested, or not if you don't want to, up to you, just wanted to say that for me these are big enough changes to deserve it.

Thank you again.

**Comment by st3no** [comment]
First of all thank you for your feedback! :)

I would like to better understand the conditions in which the exception occurs, because I do not encounter problems on my PC.
- Did you run JMarkPad from your IDE or from Gradle?
- Did you download the sources from my repo?
- Does the properties folder exist after the build?

Thanks!

**Comment by mayuso** [comment]
The properties file shouldn't have to be downloaded.

The only thing the user needs to download is the `.jar` (or the folder containing the `.exe` if they do not have Java installed).

The .jar should read `jmarkpad.properties` or create it if it does not exist. Don't worry, I'll try to fix it myself when I test all the other stuff.

**Comment by st3no** [comment]
Very well, i will keep this methodology in mind for future developments!

**Pull request merged**
